/*-----------------------------------------------------------------------------
This source file is part of Sonetto RPG Engine.

Copyright (C) 2007,2008 Arthur Carvalho de Souza Lima, Guilherme Prá Vieira


Sonetto RPG Engine is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Sonetto RPG Engine is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library; if not, write to the Free Software Foundation,
Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA or go to
http://www.gnu.org/copyleft/lesser.txt
-----------------------------------------------------------------------------*/

#ifndef __ConfigWindowImpl__
#define __ConfigWindowImpl__

/**
@file
Subclass of ConfigWindow, which is generated by wxFormBuilder.
*/

#include <wx/app.h>
#include <wx/timer.h>
#include <wx/settings.h>
#include "ConfigApp.h"
#include "AppForms.h"

namespace ConfigApplication {
    /** Implementing ConfigWindow */
class ConfigWindowImpl : public ConfigWindow {
        DECLARE_EVENT_TABLE()
        
    protected:
        ConfigApp *mApp;
        
        wxTimer   *mTimer;

        // Handlers for ConfigWindow events
        void onRsysChange(wxChoicebookEvent& event);
        void onRsysChanging(wxChoicebookEvent& event);
        void onChoiceD3D9Res(wxCommandEvent& event);
        void onChoiceD3D9AA(wxCommandEvent& event);
        void onCheckD3D9FullScreen(wxCommandEvent& event);
        void onCheckD3D9VSync(wxCommandEvent& event);
        void onChoiceOGLRes(wxCommandEvent& event);
        void onChoiceOGLColDepth(wxCommandEvent& event);
        void onChoiceOGLFreq(wxCommandEvent& event);
        void onChoiceOGLFSAA(wxCommandEvent& event);
        void onCheckOGLFullScreen(wxCommandEvent& event);
        void onCheckOGLVSync(wxCommandEvent& event);
        void onTimerEvent(wxTimerEvent& event);
        void OnClickApply(wxCommandEvent& event);
        void OnClickCancel(wxCommandEvent& event);
        void OnClickOk(wxCommandEvent& event);

    public:
        /** Constructor */
        ConfigWindowImpl(wxWindow* parent,ConfigApp *app);
    };
} // namespace

#endif // __ConfigWindowImpl__
